# Generated by Django 5.0.4 on 2024-05-28 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='completion_date',
            field=models.DateField(null=True, unique=True),
        ),
    ]
