# Generated by Django 5.0.4 on 2024-05-28 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0002_tasks_completion_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='completion_date',
            field=models.DateField(null=True),
        ),
    ]
